version: 2

sources:
  - name: raw_data_gwz
    database: uplifted-triode-475012-n7
    schema: gz_raw_data

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: raw_gz_product
        description: Products of Greenweez with their prices
        tests:
          - unique:
              column_name: products_id
          - not_null:
              column_name: products_id

      - name: raw_gz_sales
        description: Sales of Greenweez - one row per product_id found in each orders_id
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - pdt_id
                - orders_id
          - not_null:
              column_name: orders_id
          - not_null:
              column_name: pdt_id

      - name: raw_gz_ship
        description: Shipping info for Greenweez with shipping fee and other costs
        tests:
          - unique:
              column_name: orders_id
          - not_null:
              column_name: orders_id
