
version: 2

sources:
  - name: raw_data_gwz
    database: uplifted-triode-475012-n7
    schema: gz_raw_data
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: raw_gz_product
      - name: raw_gz_sales
      - name: raw_gz_ship


